---
- name: Stop and disable firewalld 
  service:
      name: firewalld
      state: stopped
      enabled: no

- name: selinux Disabled
  selinux:
    state: disabled

- name: Set Hostname
  hostname:
          name: "{{hostname}}"

- name: Entry in /etc/hosts
  lineinfile:
     path: /etc/hosts
     line: "{{ansible_host}} {{ansible_hostname}}"
      

- name: Generate ssh-key
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa 
   
- name: add the public key into Authorized_keys file to enable Key Auth
  shell: "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"
  register: addtoauth

- name: Copy Repository file
  copy: 
    src: ~/push/ambari.repo
    dest: /etc/yum.repos.d/ambari.repo

- name: Install Ambari-server
  yum:
    name: ambari-server
    state: present

- name: Ambari-server setup
  shell: ambari-server setup -s

- name: Start Ambari-server
  shell: /etc/init.d/ambari-server start
